### ISSUE TITLE
Neural Network Simple Start

### ISSUE THREAD

**Issue by Madonahs** [Madonahs/Machine-Learning#10]
## Detailed Issue :
So I was thinking we can start by doing some simple mathematics together 👍  Multiplying Matrices ,So we will have some small exercises then we can write a simple Java and Python code to help us through this: The idea is just to practice this slowly and learn together 👍 

So Let's say i Have: 

Example 1.

![matre](https://user-images.githubusercontent.com/11560987/37878404-85975798-302e-11e8-8cc1-403cfa5fd275.PNG)

Always Remember:

> Roman Catholic (Row and Columns )

**Comment by mbdhack** [comment]
Here is the solution with numpy 

import numpy  as np

A = np.array([[3,0,1],[1,2,1],[0,3,0]
    ])
B = np.array([[1,3,5],[2,0,4],[0,0,2]
    ])
print(A.dot(B))

**Comment by Madonahs** [comment]
Nice one. But it's good also for everyone to understand the concept and do it by hand too.

**Comment by Madonahs** [comment]
Hey team so this coming Weekend we can work on this issue, We will write a code to calculate that 👍  i see @mbdhack  already did the python one but we need it on the repo, 👍 I will create more exercises too so that we can play around with it.
