### ISSUE TITLE
Create an app and use Tensor flow Lite 

### ISSUE THREAD

**Issue by Madonahs** [Madonahs/Machine-Learning#34]
Advance the Sim card fraud detection.

**Comment by Madonahs** [comment]
@Nidakhan786  hello girl we can discuss this project tomorrow 👍

**Comment by Nidakhan786** [comment]
Yeah okayyy @madonahs 😊👍

**Comment by Madonahs** [comment]
@Nidakhan786  Looking forward 👍 😊

**Comment by Madonahs** [comment]
@Nidakhan786  It was super amazing speaking to you and brain-storming with you.

**Comment by Nidakhan786** [comment]
Same here @Madonahs. You are seriously an amazing person. 💯
